----- Tabela Pet: Representa os animais -----
DROP TABLE IF EXISTS PET;
CREATE TABLE PET (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PROFILE_PICTURE VARCHAR(300),
	PICTURES VARCHAR(500),
	SPECIES VARCHAR(100) NOT NULL,
	ID_BREED INTEGER,
	SIZE VARCHAR(100),
	ID_COLOR INTEGER,
	ID_DEFICIENCIES VARCHAR(500),
	NEUTERED_STATUS INTEGER,
	STAGE INTEGER,
	LAST_LOCATION VARCHAR(200),
	LAST_TIME_SEEN DATETIME(3),     
	WITH_OWNER INTEGER,
	
    PRIMARY KEY (ID)
);


----- Tabela Breed: Representa as raças -----
DROP TABLE IF EXISTS BREED;
CREATE TABLE BREED (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(255),
	
    PRIMARY KEY (ID)
);

----- Tabela Color: Representa as cores predominantes no animal -----
DROP TABLE IF EXISTS COLOR;
CREATE TABLE COLOR (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(255) NOT NULL,
	
    PRIMARY KEY (ID)
);

----- Tabela Deficiency: Representa as deficiências físicas que um animal pode ter -----
DROP TABLE IF EXISTS DEFICIENCY;
CREATE TABLE DEFICIENCY (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(255) NOT NULL,
	
    PRIMARY KEY (ID)
);