----- Tabela Breed: Representa as raças -----
DROP TABLE IF EXISTS BREED;
CREATE TABLE BREED (
	ID_BREED INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(255),
	SIZE VARCHAR(100),
	
    PRIMARY KEY (ID_BREED)
);

----- Tabela Color: Representa as cores predominantes no animal -----
DROP TABLE IF EXISTS COLOR;
CREATE TABLE COLOR (
	ID_COLOR INTEGER NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(255) NOT NULL,
	
    PRIMARY KEY (ID_COLOR)
);

----- Tabela Deficiency: Representa as deficiências físicas que um animal pode ter -----
DROP TABLE IF EXISTS DEFICIENCY;
CREATE TABLE DEFICIENCY (
	ID_DEFICIENCY INTEGER NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(255) NOT NULL,
	
    PRIMARY KEY (ID_DEFICIENCY)
);

----- Tabela Pet: Representa os animais -----
DROP TABLE IF EXISTS PET;
CREATE TABLE PET (
	ID_PET INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PROFILE_PICTURE VARCHAR(300),
	PICTURES VARCHAR(500),
	SPECIES VARCHAR(100) NOT NULL,
	ID_BREED INTEGER,
	ID_COLOR INTEGER,
	ID_DEFICIENCY INTEGER,
	NEUTERED_STATUS BOOLEAN,
	AGE INTEGER,
	LAST_LOCATION VARCHAR(200),
	LAST_TIME_SEEN DATETIME(3),     
	WITH_OWNER BOOLEAN,
	
    PRIMARY KEY (ID_PET),
    KEY BREED_FK (ID_BREED),
    KEY COLOR_FK (ID_COLOR),
    KEY DEFICIENCY_FK (ID_DEFICIENCY),
  	CONSTRAINT BREED_FK FOREIGN KEY (ID_BREED) REFERENCES BREED (ID_BREED),
  	CONSTRAINT COLOR_FK FOREIGN KEY (ID_COLOR) REFERENCES COLOR (ID_COLOR),
  	CONSTRAINT DEFICIENCY_FK FOREIGN KEY (ID_DEFICIENCY) REFERENCES DEFICIENCY (ID_DEFICIENCY)
);